language: python

python:
  - 3.7

install:
  - make virtualenv
  - pip install -r requirements_test.txt

script:
  - make test

cache:
  directories:
    - build
    - $HOME/.cache/pip

branches:
  only:
  - master

after_success:
  - python -m codecov
