language: python

os:
  - linux

python:
  - 3.7
  - 3.8

install:
  - pip install tox-travis

script:
  - make test

branches:
  only:
  - master

cache: pip

jobs:
  fast_finish: true
  allow_failures:
  - python: 3.8
