language: python

python:
  - 3.7
  - 3.8

install:
  - make virtualenv
  - pip install -r requirements_test.txt

script:
  - make test


cache:
  directories:
    - build
    - $HOME/.cache/pip

jobs:
  fast_finish: true
  allow_failures:
    - python: 3.8

branches:
  only:
  - master

after_success:
  - python -m codecov
