__name__ = "deep_reference_parser"
__version__ = "2020.2.0"
__description__ = "Deep learning model for finding and parsing references"
__url__ = "https://github.com/wellcometrust/deep_reference_parser"
__author__ = "Wellcome Trust DataLabs Team"
__author_email__ = "Grp_datalabs-datascience@Wellcomecloud.onmicrosoft.com"
__license__ = "MIT"
__model_version__ = "2019.12.0_splitting"
